### PR TITLE
Add min/max to Array class

### PR DESCRIPTION
**Pull request by lzap**
SSIA cheers.

### CODE REVIEW

**Comment by lzap** [comment]
Hello anyone? I'd like to look into other things but I have a bunch of PRs that nobody look at. @svenfuchs @kronn 

We use the gem in our project (https://theforeman.org) and we have a large and vibrant community, if you want to help with maintaining the project we can help. The core team is competent team with various skills and 2FA enabled everywhere!

**Comment by ares** [comment]
@lzap could you please rebase this? also ideally keep the alphabetical order, then I'm good to get this in

**Comment by lzap** [comment]
Done

**Comment by ares** [comment]
Thanks you, merging!

**Pull request merged**
