### PR TITLE
Various metadata updates

### PR DESCRIPTION
**Pull request by ekohl**
See individual commits for details.

### CODE REVIEW

**Review by kronn — CHANGES_REQUESTED** [review]
The gemspec is generated (with `rake gemspec:generate`) for historic reasons. Therefore these changes need the happen in the Rakefile to be persisted. Renaming the LICENSE should directly end up in the gemspec.

**Comment by ekohl** [comment]
Updated so it matches what jeweler produces. Also noticed it picked up the LICENSE as an extra rdoc file now which proves my point that various tools didn't pick it up.

**Review by kronn — APPROVED** [review]

**Comment by kronn** [comment]
@ekohl do you want or need a new release with these changes?

**Comment by ekohl** [comment]
Not strictly. I updated the RPM for 1.3.6 and noticed this when inspecting the changes. Having this upstream means I don't have to make local changes in our gem2rpm template in future updates.

**Comment by kronn** [comment]
okay. Then I won't do a release right now.

Thanks for the cleanup :-)

**Pull request merged**
