### PR TITLE
Test on Travis CI under all Ruby versions

### PR DESCRIPTION
**Pull request by domcleal**
@svenfuchs could you enable Travis CI on this repo please?

### CODE REVIEW

**Comment by kronn** [comment]
The changes itself seem fine to me. Activating the project on travis is something that is beyond my permission-level :-)

**Comment by witlessbird** [comment]
Do we still need support for 1.8.7 (and 1.9.3)? If anything, Gemfile will be smaller.

**Comment by kronn** [comment]
I am for supporting 1.8.7 and 1.9.3 unless it becomes a burden. If we see (by testing this against those version on travis) that problems arise, I would drop the support explicitely. If the gem does not work with those versions, we should state the supported versions explicitely. And while we talk about supporting specific ruby-version, we can maybe drop the "experimental"-disclaimer in the README. 

That being said, I think that all this is just a follow-up task to the initial setup on travis and should be treated as such in a separate Ticket/Issue/PR.

`</2 cents>`

**Comment by witlessbird** [comment]
Merged. Thanks, @domcleal!

**Comment by mmoll** [comment]
Travis still needs to get enabled in this repo, AFAICT.

**Comment by kronn** [comment]
I have contacted @svenfuchs via mail to get this repo enabled on travis.

**Comment by kronn** [comment]
The repo is now enabled on Travis. \o/

**Pull request merged**
