### PR TITLE
allow freeze method

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@ohadlevy @witlessbird this would fix http://projects.theforeman.org/issues/23273

**Comment by lzap** [comment]
+1 works for me!

**Comment by kronn** [comment]
This looks good to me as well. Thank you (also for the extension of the travis-yml).

**Comment by lzap** [comment]
Thanks a bunch, mind bumping up the release so we can pull the new dependency immediately?

**Comment by mmoll** [comment]
https://rubygems.org/gems/safemode shows 1.3.5 as a release from January, was there some problem back then?

**Comment by mmoll** [comment]
https://rubygems.org/gems/safemode shows 1.3.5 as a release from January, was there some problem back then?

**Comment by witlessbird** [comment]
@mmoll: not sure. 

The download count is out of whack for a gem that purportedly was released back in January. *I* wouldn't release a new version without updating version and tagging either. Lastly, 1.3.5 version currently hosted on rubygems.org contains the latest fixes. 

¯\_(ツ)_/¯

**Comment by mmoll** [comment]
OK, thanks!

**Pull request merged**
